package cn.beichenhpy.shorturl.model;

import java.io.Serializable;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

/**
 * null
 * @TableName url_info
 */
@Data
@TableName("url_info")
public class UrlInfo implements Serializable {
    /**
     *
     *
     * @mbg.generated 2021-03-01 13:57:34
     */
    @TableId(value = "id")
    private Long id;

    /**
     * 短url
     *
     * @mbg.generated 2021-03-01 13:57:34
     */
    private String shortUrl;

    /**
     * 原始url
     *
     * @mbg.generated 2021-03-01 13:57:34
     */
    private String originUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table url_info
     *
     * @mbg.generated 2021-03-01 13:57:34
     */
    private static final long serialVersionUID = 1L;
}
